name: uts
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.2.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.1
  http: ^1.1.0
  flutter_facebook_auth: ^6.0.3
  google_sign_in: ^6.2.2
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  firebase_auth_web: ^5.8.13
  js: ^0.7.1
  image_picker: ^1.1.2
  flutter_dotenv: ^5.2.1
  webview_flutter: ^4.10.0
  pdf: ^3.3.0
  path_provider: ^2.0.2
  flutter_pdfview: ^1.0.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.1"
  flutter_web_auth: ^0.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/splash_screen.json
    - assets/login.png
    - assets/pink_floyd.png
    - assets/denzel_curry.png
    - assets/logos.jpg
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logos.jpg"
  adaptive_icon_background: "#ffffff" # Optional: for Android adaptive icons
  adaptive_icon_foreground: "assets/logos.jpg" # Optional: for Android adaptive icons
  android_gravity: center # Optional: position of the image within adaptive icon
  ios_remove_alpha_ios: true # Optional: recommended for iOS icons
  web:
    generate: true # Optional: if you want to generate web icons
    image_path: "assets/logos.jpg"
    background_color: "#ffffff"
    theme_color: "#ffffff"
